name: AllTests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ASPNETCORE_ENVIRONMENT: Testing

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Dependency Restore
      run: dotnet restore
      
    - name: Project Build
      run: dotnet build

    - name: Project UnitTest
      working-directory: SmartInventoryManagementSystem.UnitTests
      run: dotnet test

    - name: Project IntegrationTest
      working-directory: SmartInventoryManagementSystem.IntegrationTests
      run: dotnet test
